### ISSUE TITLE
Allow unique indexing from the first file.

### ISSUE THREAD

**Issue by morganrallen** [rundef/node-uniquefilename#1]
At present uniquefilename will return exactly the user input for the first file, there after it will add the separator and the append character. This can causes a problem for certain glob'ing operations. `ffmpeg` for example can order input files using a template match instead of a wildcard.

```
ffmpeg -i images-%d.jpg
```

This will always miss the first file because it lacks the `-1`

I've got a simple PR, just cannot think of an appropriate name the option. `alwaysAppend: true`? Any opinion?

**Comment by rundef** [comment]
Hi,

Yes `alwaysAppend` or `forceAppend` seems appropriate.

Thank you

**Comment by rundef** [comment]
Supported in v**1.1.2**
